import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "~/styles/Home.module.css";
import Navbar from "~/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const TallComponent = () => {
  return (
    <>
      {Array.from({ length: 1000 }, (_, i) => (
        <div key={i}>{i}</div>
      ))}
    </>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} ${inter.className}`}>
        <TallComponent />
      </main>
    </>
  );
}
