import Head from "next/head";
import Image from "next/image";
import styles from "~/styles/Home.module.css";
import Navbar from "~/components/Navbar";

import Layout from "~/components/Layout";
import homePic from "../../public/home.webp";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <Layout className={styles.layout}>
        <main className={styles.main}>
          <div className={styles.header_container}>
            <h2 className={styles.header}>hello dsgasdgadsghadsgasdad</h2>
          </div>
          <div className={styles.image_container}>
            <Image
              src={homePic}
              alt="Members of the Project Heat Podcast"
              width="0"
              height="0"
              sizes="100vw"
              className={styles.image}
            />
          </div>
        </main>
      </Layout>
    </>
  );
}
